### PR TITLE
Add trafficgen-test CI workflow

### PR DESCRIPTION
**Pull request by akiselev1**
This is Github actions self-hosted runner CI workflow for the RFC2544 performance test tool.

### CODE REVIEW

**Review by dkosteck — COMMENTED** [review]
This seems like it will run with any label, right? Should we only allow it to run with "trafficgen-test" labels, for instance?

**Review by jianzzha — COMMENTED** [review]
This is a functional test; can this testbed provide a consistent bit per second throughput result?

**Comment by akiselev1** [comment]
> This is a functional test; can this testbed provide a consistent bit per second throughput result?

Do you mean - define pass/fail criteria, say less than line rate = fail?

**Comment by jianzzha** [comment]
> > This is a functional test; can this testbed provide a consistent bit per second throughput result?
> 
> Do you mean - define pass/fail criteria, say less than line rate = fail?

Yes; but you will need to have a confidence on the passing number first

**Comment by jianzzha** [comment]
or break out this test into two pieces: 1) functionally check the container build and test 2) take the test result from 1) and compare it with a predefined number (or even better, this number is an parameter that can be changed via the CI GUI

**Comment by akiselev1** [comment]
@jianzzha, @dkosteck Please take another look.

**Review by jianzzha — APPROVED** [review]

**Review by dkosteck — APPROVED** [review]
Looks good

**Pull request merged**
